server:
  port: 10086
servlet:
  context-path: /  #????????

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # ??druid???
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/website?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root123


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #???? ???????SQL
  #xml??????????xml???????
  mapper-locations: classpath*:/mapper/**/*.xml
  #???????package?????????
  typeAliasesPackage: com.example.demo4.system.entity
